### ISSUE TITLE
Superclass mismatch error when try  to start

### ISSUE THREAD

**Issue by pichotweb** [bil-bas/wrath#39]
HI,

First, congratulations for your project, i will studying your code, for learn more about game development.

I'm in trouble here, because when i try to run 'ruby bin/wrath.rbw ', it give me the error:

FATAL ERROR - TypeError: superclass mismatch for class AchievementOverlay

I'm using RVM with ruby 1.9.2-p320 for this.

Thanks!

**Comment by bil-bas** [comment]
If you want to play from the source, please roll it back to the last tagged commit, since I did some more work on the code after the last stable release and never got it working properly. Not sure that is your issue, but it can't be helping.

Not really sure why you should have an issue with it. It could be that you are using an unexpected version of Fidgit.

My working Gemfile.lock contains:

```
 chingu (0.9rc7)
  gosu (>= 0.7.33)
  gosu (>= 0.7.33)
chipmunk (5.3.4.5)
chipmunk (5.3.4.5-x86-mingw32)
clipboard (0.9.9)
ffi (1.0.9)
ffi (1.0.9-x86-mingw32)
fidgit (0.1.9)
  chingu (~> 0.9rc5)
  clipboard (~> 0.9.9)
  ffi (= 1.0.9)
  gosu (~> 0.7.33)
gosu (0.7.46)
r18n-core (0.4.12)
r18n-desktop (0.4.12)
  r18n-core (= 0.4.12)
texplay (0.4.3)
  gosu (>= 0.7.25)
texplay (0.4.3-x86-mingw32)
  gosu (>= 0.7.25)
```

Note that I'm using an unreleased version of gosu (0.7.46) because I need certain fixes in it for some Linux development I'm doing. You should be fine with 0.7.45.

**Comment by pichotweb** [comment]
Hi,

I've try to run the game through your last tagged commit as you mean, but i can't install the gem '"gosu", "~>0.7.32"', this give me the error:

(...)

checking for gl.h... no

(...)

I have this header in '/usr/include/GL/gl.h', why it's not found?

Thanks!

**Comment by bil-bas** [comment]
Sorry, that bit isn't something I can help you with. Point yourself at jlnr/gosu https://github.com/jlnr/gosu/

**Comment by pichotweb** [comment]
Ok, i'll try, in windows work. Thanks
